In [1]:
import os
import pandas as pd
import numpy as np
import re

In [2]:
datadic={}

In [3]:
cwd = os.getcwd()
train_path=cwd+'\\train_txt'
test_path=cwd+'\\test_txt'
resume_path=cwd+'\\dataset'

In [4]:
path=train_path
files=os.listdir(path)

In [5]:
###Reading 
for j in files:
    txt=open(path+'\\'+j).read()
    txt
    import re
    txt=re.split(r'[;,\s,.,),(]\s*',txt)
    txt

    import nltk
    from nltk.corpus import stopwords
    sw=stopwords.words('english')
    important=[]
    for i in txt:
        if(i.lower() not in sw):
            if(i=='' or i==' '):
                pass
            else:
                important.append(i.lower())

    one_word=important
    two_word=[important[i]+' '+important[i+1] for i in range(len(important)-1)]

    three_word=[important[i]+' '+important[i+1]+' '+important[i+2] for i in range(len(important)-2)]

    for i in one_word:
        if(datadic.get(i)==None):
            datadic[i]=1
        else:
            datadic[i]+=1
    for i in two_word:
        if(datadic.get(i)==None):
            datadic[i]=1
        else:
            datadic[i]+=1
    for i in three_word:
        if(datadic.get(i)==None):
            datadic[i]=1
        else:
            datadic[i]+=1

In [6]:
datadic

{'jacob': 1,
 'smith': 1,
 'fresher': 60,
 'personal': 45,
 'profile': 129,
 'actively': 4,
 'seeking': 13,
 'opportunity': 11,
 'data': 654,
 'analyst': 134,
 'machine': 353,
 'learning': 461,
 'engineer': 119,
 'goal': 2,
 'discover': 1,
 'new': 12,
 'business': 125,
 'strategies': 5,
 'create': 11,
 'impact': 5,
 'driven': 5,
 'analytical': 16,
 'decisions': 7,
 'leading': 3,
 'success': 2,
 'work': 117,
 'background': 27,
 'experts': 2,
 'hub': 2,
 'intern': 66,
 'may': 25,
 '2019': 177,
 'part': 14,
 'team': 23,
 'designed': 5,
 'developed': 18,
 'smart': 7,
 'parking': 2,
 'system': 50,
 'based': 64,
 'object': 10,
 'recognition': 24,
 'skills': 173,
 'python': 203,
 'sql': 61,
 'mysql': 16,
 'tableau': 37,
 'power': 16,
 'bi': 15,
 'pandas': 18,
 'numpy': 21,
 'matplotlib': 15,
 'excel': 17,
 'aws': 35,
 'emr': 1,
 'ec2': 5,
 's3': 1,
 'cloud': 26,
 'hive': 8,
 'hql': 1,
 'education': 108,
 'b': 138,
 'tech': 129,
 'ece': 7,
 'vit-ap': 3,
 'university': 85,
 '2020': 139,
 'projects': 162,
 'music': 4,
 'genre': 2,
 'classification': 25,
 'face': 11,
 'eye': 2,
 'smile': 2,
 'activities': 82,
 'deep': 94,
 'masters': 4,
 'jacob smith': 1,
 'smith fresher': 1,
 'fresher personal': 2,
 'personal profile': 22,
 'profile actively': 2,
 'actively seeking': 3,
 'seeking opportunity': 1,
 'opportunity data': 2,
 'data analyst': 54,
 'analyst machine': 6,
 'machine learning': 346,
 'learning engineer': 47,
 'engineer goal': 1,
 'goal discover': 1,
 'discover new': 1,
 'new business': 1,
 'business strategies': 3,
 'strategies create': 1,
 'create impact': 1,
 'impact data': 1,
 'data driven': 4,
 'driven analytical': 1,
 'analytical decisions': 1,
 'decisions leading': 1,
 'leading business': 1,
 'business success': 1,
 'success work': 1,
 'work background': 22,
 'background experts': 1,
 'experts hub': 2,
 'hub intern': 2,
 'intern may': 8,
 'may 2019': 11,
 '2019 part': 2,
 'part team': 5,
 'team designed': 3,
 'designed developed': 1,
 'developed smart': 1,
 'smart parking': 2,
 'parking system': 2,
 'system based': 2,
 'based object': 2,
 'object recognition': 2,
 'recognition skills': 1,
 'skills python': 17,
 'python sql': 16,
 'sql mysql': 2,
 'mysql tableau': 2,
 'tableau power': 6,
 'power bi': 13,
 'bi pandas': 1,
 'pandas numpy': 5,
 'numpy matplotlib': 1,
 'matplotlib excel': 1,
 'excel machine': 2,
 'learning aws': 2,
 'aws emr': 1,
 'emr ec2': 1,
 'ec2 s3': 1,
 's3 cloud': 1,
 'cloud hive': 1,
 'hive hql': 1,
 'hql excel': 1,
 'excel education': 1,
 'education b': 93,
 'b tech': 109,
 'tech ece': 6,
 'ece vit-ap': 2,
 'vit-ap university': 2,
 'university 2020': 8,
 '2020 projects': 12,
 'projects music': 3,
 'music genre': 2,
 'genre classification': 2,
 'classification face': 2,
 'face eye': 2,
 'eye smile': 2,
 'smile recognition': 2,
 'recognition activities': 3,
 'activities deep': 5,
 'deep learning': 93,
 'learning masters': 2,
 'masters machine': 3,
 'jacob smith fresher': 1,
 'smith fresher personal': 1,
 'fresher personal profile': 2,
 'personal profile actively': 1,
 'profile actively seeking': 2,
 'actively seeking opportunity': 1,
 'seeking opportunity data': 1,
 'opportunity data analyst': 1,
 'data analyst machine': 3,
 'analyst machine learning': 6,
 'machine learning engineer': 44,
 'learning engineer goal': 1,
 'engineer goal discover': 1,
 'goal discover new': 1,
 'discover new business': 1,
 'new business strategies': 1,
 'business strategies create': 1,
 'strategies create impact': 1,
 'create impact data': 1,
 'impact data driven': 1,
 'data driven analytical': 1,
 'driven analytical decisions': 1,
 'analytical decisions leading': 1,
 'decisions leading business': 1,
 'leading business success': 1,
 'business success work': 1,
 'success work background': 1,
 'work background experts': 1,
 'background experts hub': 1,
 'experts hub intern': 2,
 'hub intern may': 2,
 'intern may 2019': 2,
 'may 2019 part': 1,
 '2019 part team': 1,
 'part team designed': 3,
 'team designed developed': 1,
 'designed developed smart': 1,
 'developed smart parking': 1,
 'smart parking system': 2,
 'parking system based': 1,
 'system based object': 1,
 'based object recognition': 1,
 'object recognition skills': 1,
 'recognition skills python': 1,
 'skills python sql': 1,
 'python sql mysql': 1,
 'sql mysql tableau': 1,
 'mysql tableau power': 1,
 'tableau power bi': 6,
 'power bi pandas': 1,
 'bi pandas numpy': 1,
 'pandas numpy matplotlib': 1,
 'numpy matplotlib excel': 1,
 'matplotlib excel machine': 1,
 'excel machine learning': 2,
 'machine learning aws': 1,
 'learning aws emr': 1,
 'aws emr ec2': 1,
 'emr ec2 s3': 1,
 'ec2 s3 cloud': 1,
 's3 cloud hive': 1,
 'cloud hive hql': 1,
 'hive hql excel': 1,
 'hql excel education': 1,
 'excel education b': 1,
 'education b tech': 78,
 'b tech ece': 6,
 'tech ece vit-ap': 2,
 'ece vit-ap university': 2,
 'vit-ap university 2020': 1,
 'university 2020 projects': 2,
 '2020 projects music': 1,
 'projects music genre': 2,
 'music genre classification': 2,
 'genre classification face': 2,
 'classification face eye': 2,
 'face eye smile': 2,
 'eye smile recognition': 2,
 'smile recognition activities': 1,
 'recognition activities deep': 1,
 'activities deep learning': 5,
 'deep learning masters': 2,
 'learning masters machine': 2,
 'masters machine learning': 3,
 'brianna': 1,
 'williams': 3,
 'junior': 53,
 'developer': 96,
 'executive': 44,
 'curiosity-driven': 1,
 'scientist': 37,
 'eager': 1,
 'leverage': 6,
 'analytics': 114,
 'extract': 6,
 'meaningful': 4,
 'insights': 18,
 'make': 7,
 'informed': 5,
 'solve': 9,
 'challenging': 7,
 'problems': 38,
 'ensure': 1,
 'contribute': 11,
 'knowledge': 28,
 'logical': 1,
 'thinking': 2,
 'towards': 14,
 'consistent': 1,
 'growth': 8,
 'development': 64,
 'organization': 6,
 'enhance': 2,
 'experience': 138,
 'continuous': 2,
 'teamwork': 1,
 'analysis': 194,
 'mining': 39,
 'natural': 62,
 'language': 63,
 'processing': 83,
 'linear': 19,
 'regression': 48,
 'cluster': 2,
 'correlation': 4,
 'logistic': 14,
 'principal': 1,
 'component': 2,
 'anova': 1,
 'neural': 27,
 'networks': 27,
 'r': 36,
 'spss': 3,
 'decision': 12,
 'tree': 2,
 'trained': 4,
 'big': 24,
 'hadoop': 7,
 'a-1': 1,
 'level': 13,
 'certificate': 9,
 'chatbot': 9,
 'customer': 21,
 'feedback': 1,
 'responses': 2,
 'mirror': 1,
 'jewelry': 1,
 'kpmmc': 1,
 'inc': 2,
 'aug': 11,
 '-': 102,
 'ongoing': 26,
 'engineered': 1,
 'nlp': 53,
 'solution': 21,
 'took': 3,
 'kind': 2,
 'text': 41,
 'input': 2,
 'found': 1,
 'top': 1,
 '5': 2,
 'questions': 1,
 'answers': 1,
 'similar': 1,
 'contributed': 5,
 'internal': 3,
 'also': 25,
 'bsc': 7,
 'ca': 9,
 'mamco': 2,
 'kerala': 5,
 '2018': 49,
 'msc': 8,
 'brianna williams': 1,
 'williams junior': 1,
 'junior developer': 7,
 'developer executive': 4,
 'executive profile': 22,
 'profile curiosity-driven': 1,
 'curiosity-driven data': 1,
 'data scientist': 36,
 'scientist eager': 1,
 'eager leverage': 1,
 'leverage machine': 1,
 'learning data': 25,
 'data analytics': 50,
 'analytics extract': 1,
 'extract meaningful': 1,
 'meaningful insights': 2,
 'insights make': 1,
 'make informed': 1,
 'informed decisions': 1,
 'decisions solve': 1,
 'solve challenging': 1,
 'challenging business': 1,
 'business problems': 9,
 'problems ensure': 1,
 'ensure contribute': 1,
 'contribute knowledge': 1,
 'knowledge logical': 1,
 'logical thinking': 1,
 'thinking analytical': 1,
 'analytical skills': 6,
 'skills towards': 1,
 'towards consistent': 1,
 'consistent growth': 1,
 'growth development': 1,
 'development organization': 1,
 'organization enhance': 1,
 'enhance experience': 1,
 'experience continuous': 1,
 'continuous learning': 1,
 'learning teamwork': 1,
 'teamwork skills': 1,
 'skills data': 49,
 'data analysis': 64,
 'analysis machine': 19,
 'data mining': 32,
 'mining natural': 3,
 'natural language': 60,
 'language processing': 58,
 'processing linear': 1,
 'linear regression': 18,
 'regression cluster': 1,
 'cluster analysis': 1,
 'analysis correlation': 1,
 'correlation analysis': 1,
 'analysis logistic': 1,
 'logistic regression': 14,
 'regression principal': 1,
 'principal component': 1,
 'component analysis': 2,
 'analysis anova': 1,
 'anova neural': 1,
 'neural networks': 24,
 'networks r': 1,
 'r python': 6,
 'python mysql': 6,
 'tableau excel': 1,
 'excel spss': 1,
 'spss decision': 1,
 'decision tree': 2,
 'tree activities': 1,
 'activities trained': 1,
 'trained big': 1,
 'big data': 24,
 'analysis hadoop': 1,
 'hadoop a-1': 1,
 'a-1 level': 1,
 'level certificate': 1,
 'certificate projects': 2,
 'projects chatbot': 1,
 'chatbot customer': 1,
 'customer feedback': 1,
 'feedback responses': 1,
 'responses smart': 1,
 'smart mirror': 1,
 'mirror jewelry': 1,
 'jewelry work': 1,
 'work experience': 66,
 'experience kpmmc': 1,
 'kpmmc inc': 1,
 'inc machine': 1,
 'learning junior': 1,
 'developer aug': 2,
 'aug 2020': 6,
 '2020 -': 23,
 '- ongoing': 21,
 'ongoing engineered': 1,
 'engineered nlp': 1,
 'nlp solution': 1,
 'solution took': 1,
 'took kind': 1,
 'kind text': 1,
 'text input': 1,
 'input found': 1,
 'found top': 1,
 'top 5': 1,
 '5 questions': 1,
 'questions answers': 1,
 'answers similar': 1,
 'similar contributed': 1,
 'contributed internal': 1,
 'internal projects': 1,
 'projects also': 2,
 'also education': 1,
 'education bsc': 4,
 'bsc ca': 2,
 'ca mamco': 2,
 'mamco university': 2,
 'university kerala': 2,
 'kerala 2018': 1,
 '2018 msc': 2,
 'msc ca': 1,
 'kerala 2020': 1,
 'brianna williams junior': 1,
 'williams junior developer': 1,
 'junior developer executive': 3,
 'developer executive profile': 2,
 'executive profile curiosity-driven': 1,
 'profile curiosity-driven data': 1,
 'curiosity-driven data scientist': 1,
 'data scientist eager': 1,
 'scientist eager leverage': 1,
 'eager leverage machine': 1,
 'leverage machine learning': 1,
 'machine learning data': 19,
 'learning data analytics': 3,
 'data analytics extract': 1,
 'analytics extract meaningful': 1,
 'extract meaningful insights': 1,
 'meaningful insights make': 1,
 'insights make informed': 1,
 'make informed decisions': 1,
 'informed decisions solve': 1,
 'decisions solve challenging': 1,
 'solve challenging business': 1,
 'challenging business problems': 1,
 'business problems ensure': 1,
 'problems ensure contribute': 1,
 'ensure contribute knowledge': 1,
 'contribute knowledge logical': 1,
 'knowledge logical thinking': 1,
 'logical thinking analytical': 1,
 'thinking analytical skills': 1,
 'analytical skills towards': 1,
 'skills towards consistent': 1,
 'towards consistent growth': 1,
 'consistent growth development': 1,
 'growth development organization': 1,
 'development organization enhance': 1,
 'organization enhance experience': 1,
 'enhance experience continuous': 1,
 'experience continuous learning': 1,
 'continuous learning teamwork': 1,
 'learning teamwork skills': 1,
 'teamwork skills data': 1,
 'skills data analysis': 17,
 'data analysis machine': 10,
 'analysis machine learning': 19,
 'learning data mining': 3,
 'data mining natural': 2,
 'mining natural language': 3,
 'natural language processing': 58,
 'language processing linear': 1,
 'processing linear regression': 1,
 'linear regression cluster': 1,
 'regression cluster analysis': 1,
 'cluster analysis correlation': 1,
 'analysis correlation analysis': 1,
 'correlation analysis logistic': 1,
 'analysis logistic regression': 1,
 'logistic regression principal': 1,
 'regression principal component': 1,
 'principal component analysis': 1,
 'component analysis anova': 1,
 'analysis anova neural': 1,
 'anova neural networks': 1,
 'neural networks r': 1,
 'networks r python': 1,
 'r python mysql': 1,
 'python mysql tableau': 1,
 'mysql tableau excel': 1,
 'tableau excel spss': 1,
 'excel spss decision': 1,
 'spss decision tree': 1,
 'decision tree activities': 1,
 'tree activities trained': 1,
 'activities trained big': 1,
 'trained big data': 1,
 'big data analysis': 2,
 'data analysis hadoop': 1,
 'analysis hadoop a-1': 1,
 'hadoop a-1 level': 1,
 'a-1 level certificate': 1,
 'level certificate projects': 1,
 'certificate projects chatbot': 1,
 'projects chatbot customer': 1,
 'chatbot customer feedback': 1,
 'customer feedback responses': 1,
 'feedback responses smart': 1,
 'responses smart mirror': 1,
 'smart mirror jewelry': 1,
 'mirror jewelry work': 1,
 'jewelry work experience': 1,
 'work experience kpmmc': 1,
 'experience kpmmc inc': 1,
 'kpmmc inc machine': 1,
 'inc machine learning': 1,
 'machine learning junior': 1,
 'learning junior developer': 1,
 'junior developer aug': 1,
 'developer aug 2020': 1,
 'aug 2020 -': 1,
 '2020 - ongoing': 11,
 '- ongoing engineered': 1,
 'ongoing engineered nlp': 1,
 'engineered nlp solution': 1,
 'nlp solution took': 1,
 'solution took kind': 1,
 'took kind text': 1,
 'kind text input': 1,
 'text input found': 1,
 'input found top': 1,
 'found top 5': 1,
 'top 5 questions': 1,
 '5 questions answers': 1,
 'questions answers similar': 1,
 'answers similar contributed': 1,
 'similar contributed internal': 1,
 'contributed internal projects': 1,
 'internal projects also': 1,
 'projects also education': 1,
 'also education bsc': 1,
 'education bsc ca': 2,
 'bsc ca mamco': 1,
 'ca mamco university': 2,
 'mamco university kerala': 2,
 'university kerala 2018': 1,
 'kerala 2018 msc': 1,
 '2018 msc ca': 1,
 'msc ca mamco': 1,
 'university kerala 2020': 1,
 'mason': 2,
 'quadrado': 1,
 'associate': 40,
 'certified': 12,
 'degree': 10,
 'electronics': 12,
 'engineering': 57,
 'hands': 5,
 'analyzing': 13,
 '&': 48,
 'interpreting': 3,
 'good': 13,
 'numerical': 2,
 'accuracy': 6,
 'computer': 48,
 'vision': 30,
 'flask': 12,
 'api': 8,
 'predictive': 33,
 'modeling': 38,
 'scikit-learn': 4,
 'statistical': 38,
 'multivariate': 2,
 'trees': 3,
 'random': 5,
 'forest': 4,
 'xgboost': 2,
 'project': 41,
 'pattern': 9,
 'matching': 2,
 'auto-color': 1,
 'grading': 1,
 'using': 131,
 'qualification': 14,
 'google': 9,
 'amz': 2,
 'loans': 4,
 'mortgages': 2,
 'erc': 2,
 'jun': 17,
 'till': 56,
 'date': 59,
 'handling': 10,
 'employees': 2,
 'finding': 6,
 'retention': 3,
 'factors': 2,
 'employee': 5,
 'satisfaction': 7,
 'worked': 47,
 'closely': 5,
 'hr': 2,
 'find': 9,
 'balance': 1,
 'beneficial': 1,
 'company': 16,
 'tech/b': 4,
 'e': 12,
 'electronics/telecommunication': 6,
 'nagpur': 4,
 'mason quadrado': 1,
 'quadrado associate': 1,
 'associate analyst': 1,
 'analyst certified': 1,
 'certified data': 5,
 'analyst degree': 1,
 'degree electronics': 3,
 'electronics engineering': 2,
 'engineering hands': 1,
 'hands experience': 3,
 'experience analyzing': 1,
 'analyzing &': 1,
 '& interpreting': 1,
 'interpreting data': 1,
 'data good': 1,
 'good numerical': 1,
 'numerical accuracy': 1,
 'accuracy skills': 2,
 'python machine': 12,
 'learning mysql': 2,
 'mysql data': 1,
 'mining deep': 6,
 'analysis computer': 2,
 'computer vision': 30,
 'vision flask': 1,
 'flask api': 2,
 'api predictive': 1,
 'predictive modeling': 13,
 'modeling aws': 1,
 'aws scikit-learn': 2,
 'scikit-learn numpy': 2,
 'numpy statistical': 1,
 'statistical analysis': 17,
 'analysis multivariate': 1,
 'multivariate analysis': 2,
 'analysis decision': 1,
 'decision trees': 3,
 'trees random': 2,
 'random forest': 4,
 'forest xgboost': 2,
 'xgboost nlp': 1,
 'nlp project': 2,
 'project deep': 1,
 'learning based': 3,
 'based pattern': 1,
 'pattern matching': 1,
 'matching auto-color': 1,
 'auto-color grading': 1,
 'grading using': 1,
 'using python': 13,
 'python qualification': 1,
 'qualification google': 1,
 'google cloud': 3,
 'cloud certified': 1,
 'certified work': 1,
 'experience amz': 2,
 'amz loans': 2,
 'loans mortgages': 2,
 'mortgages erc': 1,
 'erc analytics': 1,
 'analytics jun': 1,
 'jun 2019': 8,
 '2019 till': 23,
 'till date': 56,
 'date handling': 2,
 'handling data': 2,
 'data employees': 1,
 'employees finding': 1,
 'finding retention': 1,
 'retention factors': 1,
 'factors employee': 1,
 'employee satisfaction': 2,
 'satisfaction worked': 1,
 'worked closely': 2,
 'closely hr': 1,
 'hr team': 1,
 'team find': 2,
 'find balance': 1,
 'balance beneficial': 1,
 'beneficial employees': 1,
 'employees company': 1,
 'company education': 1,
 'b tech/b': 4,
 'tech/b e': 4,
 'e electronics/telecommunication': 1,
 'electronics/telecommunication nagpur': 1,
 'nagpur university': 4,
 'university 2019': 17,
 'mason quadrado associate': 1,
 'quadrado associate analyst': 1,
 'associate analyst certified': 1,
 'analyst certified data': 1,
 'certified data analyst': 2,
 'data analyst degree': 1,
 'analyst degree electronics': 1,
 'degree electronics engineering': 2,
 'electronics engineering hands': 1,
 'engineering hands experience': 1,
 'hands experience analyzing': 1,
 'experience analyzing &': 1,
 'analyzing & interpreting': 1,
 '& interpreting data': 1,
 'interpreting data good': 1,
 'data good numerical': 1,
 'good numerical accuracy': 1,
 'numerical accuracy skills': 1,
 'accuracy skills python': 2,
 'skills python machine': 5,
 'python machine learning': 12,
 'machine learning mysql': 1,
 'learning mysql data': 1,
 'mysql data mining': 1,
 'data mining deep': 6,
 'mining deep learning': 6,
 'deep learning data': 6,
 'learning data analysis': 6,
 'data analysis computer': 2,
 'analysis computer vision': 2,
 'computer vision flask': 1,
 'vision flask api': 1,
 'flask api predictive': 1,
 'api predictive modeling': 1,
 'predictive modeling aws': 1,
 'modeling aws scikit-learn': 1,
 'aws scikit-learn numpy': 2,
 'scikit-learn numpy statistical': 1,
 'numpy statistical analysis': 1,
 'statistical analysis multivariate': 1,
 'analysis multivariate analysis': 1,
 'multivariate analysis decision': 1,
 'analysis decision trees': 1,
 'decision trees random': 2,
 'trees random forest': 2,
 'random forest xgboost': 2,
 'forest xgboost nlp': 1,
 'xgboost nlp project': 1,
 'nlp project deep': 1,
 'project deep learning': 1,
 'deep learning based': 1,
 'learning based pattern': 1,
 'based pattern matching': 1,
 'pattern matching auto-color': 1,
 'matching auto-color grading': 1,
 'auto-color grading using': 1,
 'grading using python': 1,
 'using python qualification': 1,
 'python qualification google': 1,
 'qualification google cloud': 1,
 'google cloud certified': 1,
 'cloud certified work': 1,
 'certified work experience': 1,
 'work experience amz': 2,
 'experience amz loans': 2,
 'amz loans mortgages': 2,
 'loans mortgages erc': 1,
 'mortgages erc analytics': 1,
 'erc analytics jun': 1,
 'analytics jun 2019': 1,
 'jun 2019 till': 2,
 '2019 till date': 23,
 'till date handling': 2,
 'date handling data': 1,
 'handling data employees': 1,
 'data employees finding': 1,
 'employees finding retention': 1,
 'finding retention factors': 1,
 'retention factors employee': 1,
 'factors employee satisfaction': 1,
 'employee satisfaction worked': 1,
 'satisfaction worked closely': 1,
 'worked closely hr': 1,
 'closely hr team': 1,
 'hr team find': 1,
 'team find balance': 1,
 'find balance beneficial': 1,
 'balance beneficial employees': 1,
 'beneficial employees company': 1,
 'employees company education': 1,
 'company education b': 1,
 'education b tech/b': 2,
 'b tech/b e': 4,
 'tech/b e electronics/telecommunication': 1,
 'e electronics/telecommunication nagpur': 1,
 'electronics/telecommunication nagpur university': 1,
 'nagpur university 2019': 4,
 'rodney': 1,
 'michaels': 2,
 'software': 112,
 'java': 27,
 'c++': 24,
 'sap': 12,
 'iot': 3,
 'automatically': 1,
 'turned': 1,
 'speech': 4,
 'tone': 1,
 'extremely': 1,
 'motivated': 6,
 'constantly': 1,
 'develop': 3,
 'grow': 4,
 'professionally': 1,
 'confident': 1,
 'ability': 4,
 'come': 2,
 'innovative': 3,
 'solutions': 53,
 'maintain': 2,
 'better': 10,
 'practices': 2,
 '-machine': 1,
 'acs': 2,
 'pvt': 15,
 'ltd': 22,
 'communication': 8,
 'edge': 5,
 'devices': 5,
 'requests': 1,
 'mqtt': 1,
 'allocation': 3,
 'estimation': 2,
 'involved': 4,
 'architectural': 1,
 'design': 12,

In [7]:
import pandas as pd
words=datadic.keys()
freq=datadic.values()
table=pd.DataFrame({'Word':words,'freq':freq})
#table['freq']=table['freq']/sum(table['freq'])

In [8]:
table.sort_values(['freq'],ascending=False)#.to_csv('tmp.csv',index=False)

                                Word  freq
8                               data   654
11                          learning   461
10                           machine   353
87                  machine learning   346
43                            python   203
...                              ...   ...
9749              based remark based     1
9748          customers based remark     1
9747    satisfaction customers based     1
9746   sector satisfaction customers     1
24727        activities ksst scholar     1

[24728 rows x 2 columns]

In [9]:
tp=table[table['freq']>5]

In [10]:
words=list(tp['Word'])
freq=list(tp['freq'])
n=len(words)
word_filter=[]
freq_filter=[]

In [11]:
for i in range(n):
    curr=None
    curr_freq=None
    remove=[]
    for j in range(i+1,n):
        flag=0
        if(words[i] in words[j]):
            for k in word_filter:
                if(k in words[i]):
                    flag=1
            if(flag==1):
                pass
            elif(freq[i]>freq[j]):
                curr_freq=freq[i]
                curr=words[i]
                remove.append(words[j])
            else:
                curr_freq=freq[j]
                curr=words[j]
    if(curr):
        word_filter.append(curr)
        freq_filter.append(freq)

In [12]:
word_filter
finalwords=[]
for i in word_filter:
    if(not i.isnumeric()):
        finalwords.append(i)

In [13]:
features=[x for x in finalwords if(len(x)>1)]

In [14]:
features=list(set(features))

In [15]:
#-----------------------------------------------------------------------------------------------#

In [16]:
train_data=pd.read_csv('dataset/train.csv')
train_data

      CandidateID  Match Percentage
0   candidate_011             13.60
1   candidate_113             36.63
2   candidate_123             54.93
3   candidate_012             41.46
4   candidate_002             48.91
..            ...               ...
85  candidate_133             54.20
86  candidate_137             60.18
87  candidate_072             44.94
88  candidate_140             11.41
89  candidate_037             56.70

[90 rows x 2 columns]

In [17]:
train_path

'C:\\Users\\16063\\Desktop\\ML\\HE Data Science\\A perfet fit\\train_txt'

In [18]:
train_files=train_data['CandidateID']
train_score=train_data['Match Percentage']

In [19]:
word_score={}

In [ ]:
k=0
for i in train_files:
    print('-----------------------------------')
    txt=open(train_path+'\\'+i+'.txt').read()
    import re
    txt=re.split(r'[;,\s,.,),(]\s*',txt)
    words=[x.lower() for x in txt]
    #print(txt)
    for j in features:
        if(j in words):
            if(word_score.get(j)==None):
                word_score[j]=[1,train_score[k]]
            else:
                word_score[j][0]+=1
                word_score[j][1]+=train_score[k]
    k+=1

In [ ]:
word_score

In [ ]:
word_score_tmp={}

In [ ]:
for i in word_score.keys():
    word_score_tmp[i]=word_score[i][1]/word_score[i][0]

In [ ]:
word_score_tmp

In [ ]:
txt=open(train_path+'\\'+'candidate_113'+'.txt').read()
import re
txt=re.split(r'[;,\s,.,),(]\s*',txt)
words=[x.lower() for x in txt]
sum=0
for i in words:
    if(word_score_tmp.get(i)):
        sum+=word_score_tmp[i]

In [25]:
features
ft=''
for i in features:
    ft=ft+','+i

In [29]:
feature_list_txt = open("Myfeatures.txt","a")
feature_list_txt.write(ft)
feature_list_txt.close()

In [30]:
ft

',engineer,object,intelligence,date,created,logistic regression,learning,sc,pvt ltd,processing,matplotlib,background,junior,like,analyst,ltd,looking,numpy,sql,aug,time,extraction,may,machine,fresher,scientist,process,would,clients,personal,recognition,text,natural,pandas,experience,model,achievements,tech,python,linear,science,education,deep,regression,neural,data,management,jul,analysis,always,models,profile,skills,analytics,well,till,power,manipulation,nlp,ml,system,vision,development,college,employment history,using,nov,business,ca,detection,work,mining,cleaning,intern,end,analytical,tableau,ongoing,pipeline,jan,projects,modeling,developer,assistant,ai,oct,jun,dec,language,institute,activities,executive,solutions,associate,image,java,scikit learn,ece,visualization,university,powerbi,multiple'